### ISSUE TITLE
做微服务改造时 遇到一些问题

### ISSUE THREAD

**Issue by DragonTeeth** [ServiceComb/ServiceComb.github.io#110]
背景：
原来的工程使用的是原生的 httpclient ，在改造成ServiceStage的restTemplate时遇到了一些问题。麻烦看看这些问题是否可以解决。

uam发布服务接口，目前碰到如下问题：
1、ServletOutputStream不行，必须使用确定的类，接口或抽象类不能使用
2、响应对象中有Object不行，包括Map<String,Object>这种
3、重载方法不行，方法名称必须不重复
4、方法参数名称必须是确定的对象，不能用接口或者抽象类

这个是今天发现的问题
一个controller中提供的接口过多出现如下错误：
Bad Request, description: http: request body too large。
导致启动失败。
测试的controller里大概有10来方法。

另外，遇到个问题，之前写测试方法的时候是通的，
今儿全部不通了，一直是如下错误：
java.lang.Error: not support def type: class io.swagger.models.properties.BaseIntegerProperty
日志上看没到服务端，直接在客户端就出错了。

**Comment by WillemJiang** [comment]
相关问题的讨论请移步 https://github.com/ServiceComb/ServiceComb-Java-Chassis/issues/210
这里主要是处理跟网站相关的问题。
