### ISSUE TITLE
例子中建议使用最新或配套的ServiceComb-Java-Chassis和Service Center版本

### ISSUE THREAD

**Issue by MabinGo** [ServiceComb/ServiceComb.github.io#157]
环境配置->运行Service Center ，按照此处的指南操作

场景：如果使用第1种方式下载Service Center的可执行文件，下载的版本为 service-center-0.1.1 ，该版本与较新的ServiceComb-Java-Chassis 0.4.0版本配套使用。

问题：在通过cse://serviceName/appPath发送请求时失败，抛出 java.lang.Error:not support def type:calss io.swagger.models.properties BaseIntegerProperty 异常。

措施：在将Service Center 升级到0.4.0版本后问题得到解决。

建议：修改“ 环境配置->运行Service Center ”的描述，推荐用户使用新版本的Service Center，并说明新老版本搭配可能引入的问题。

**Comment by eric-lee-ltk** [comment]
I think move the question and its answer to FAQ instead of showing in the setup environment page is better.
